package com.sterp.multitenant.tenant.common.dao;

import java.util.List;
import java.util.Map;

import com.sterp.multitenant.tenant.dto.CommonDropdownResponseDataTravelObject;
import com.sterp.multitenant.tenant.dto.CommonDropdownResponseDto;
import com.sterp.multitenant.tenant.dto.CommonPagingResponse;
import com.sterp.multitenant.tenant.settings.template.entity.dto.DefaultSortDto;
import com.sterp.multitenant.tenant.settings.template.entity.dto.ScreenFilterDTO;

public interface CommonDao {

	public Object add(Object obj);

	public Object update(Object obj);

	public <T> CommonPagingResponse<T> getCommonFilteredList(Class<T> T, int page, int limit, String search, Map<String, Object> advanceSearch,
			 Map<String, Object> advanceSearchAnd,
			String sort, String order, List<ScreenFilterDTO> screenFilterDTO, long moduleId, Map<String, Object> groupSort, DefaultSortDto defaultSort, long userId, Map<String, Object> customFilter);

	public List<CommonDropdownResponseDataTravelObject> getSelectionList(String queryString);

	public <T> T getById(Class<T> T, Long id);

	public List<CommonDropdownResponseDto> getAutogeneratedFields(String T, long moduleId);

	public <T> String getLastGeneratedCode(Class<T> T, Long branchId, Long companyId, String field);

	public <R> String getLastGeneratedCode(Class<R> R, long refDocId, String field);

	public <T> List<T> getCommonList(Class<T> T);

	List getCommonListByNativeQuery();

	public <T> List<T> getCustomFieldByModuleId(Class<T> T, Long moduleId);

	public <T> List<T> getByFilters(Class<T> T, Map<String, Object> filters);

	public String getFolderFields(long moduleId);

}
