multitenancy:
  mtapp:
    master:
      datasource:
        #url: jdbc:mysql://mysql/shivit_super_admin?allowPublicKeyRetrieval=true&useSSL=false
        url: jdbc:mysql://localhost:3306/shivit_super_admin?allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: Shivit@12
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool
        
        
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
    - http://localhost:4200/oauth2/redirect


   